config/routes.rb
Rentals::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}
  

  root to: 'welcome#index'

  get 'mr_rogers' => 'mr_rogers/dashboard#index'
  
  namespace :mr_rogers do
    resources :rentals do
      post 'publish'
      post 'unpublish'
    end
    resources :photos, except: [:edit]
  end

  get 'rentals/pet_friendly' => 'rentals#index', pet_friendly: true, as: 'pet_friendly_rentals'
  get 'rentals/kid_friendly' => 'rentals#index', kid_friendly: true, as: 'kid_friendly_rentals'
  get 'rentals/long_term' => 'rentals#index', long_term: true, as: 'long_term_rentals'
  resources :rentals, only: [:show, :index]
  resources :contacts, only: [:create]
end

app/models/rental.rb
class Rental < ActiveRecord::Base
  validates :name, presence: true, :length => { :in => 2..255 }
  validates :description, presence: true, :length => { :in => 50..255 }
  validates :contact, presence: true, :length => { :in => 5..255 }
  
  has_many :photos, :dependent => :destroy

  scope :featured, -> { includes(:photos).where('photos.featured is true').references(:photos) }
  scope :banner, -> { includes(:photos).where('photos.banner is true').references(:photos) }
  scope :pet_friendly, -> { where(pet_friendly: true) }
  scope :kid_friendly, -> { where(kid_friendly: true) }
  scope :long_term, -> { where(long_term: true) }
  scope :published, -> { where(published: true) }

  def featured_photo
    if photos.empty?
      ''
    elsif photos.featured.empty?
      photos.first
    else
      photos.featured.first
    end
  end
  
  def banner_photo
    if photos.empty?
      ''
    elsif photos.banner.empty?
      photos.first
    else
      photos.banner.first
    end
  end
  
  def publish!
    update_attribute(:published, true) if photos.count > 0
  end

  def unpublish!
    update_attribute(:published, false)
  end
end

app/controllers/mr_rogers/rentals_controller.rb
class MrRogers::RentalsController < MrRogers::ApplicationController
  respond_to :html
  
  def index
    respond_to do |format|
      format.html
      format.json { render json: RentalsDatatable.new(view_context) }
    end
  end
  
  def new
    @rental = Rental.new
  end
  
  def create
    @rental = Rental.create(post_params)
    flashy(@rental)
    @rental.errors.empty? ? (redirect_to action: :index) : (render :new)
  end

  def edit
    @rental = Rental.find(params[:id])
  end

  def update
    @rental = Rental.find(params[:id])
    @rental.update_attributes(post_params)
    flashy(@rental)
    render :edit
  end

  def publish
    @rental = Rental.find(params[:rental_id])
    @rental.publish!
    if @rental.published?
      flash[:success] = 'Published Successfully'
    else
      flash[:error] = 'Could not publish the rental. Check your data and try again.'
    end
    render :edit
  end

  def unpublish
    @rental = Rental.find(params[:rental_id])
    @rental.unpublish!
    if @rental.published?
      flash[:error] = 'Could not un-publish the rental for an unknown reason.'
    else
      flash[:success] = 'Un-Published Successfully'
    end
    render :edit
  end

  
  def destroy
    Rental.find(params[:id]).destroy
    flash[:success] = 'The rental has been deleted'
    redirect_to action: :index
  end

  private
    def post_params
       params.require(:rental).permit(:name, :description, :pet_friendly, :kid_friendly, :long_term, :bedrooms, :bathrooms, :rate_per_night, :rate_per_week, :rate_per_month, :contact, :base_rate_per_night, :base_rate_per_month, :base_rate_per_week, :published)
    end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  def index
    if params[:pet_friendly]
      @rentals = Rental.published.pet_friendly
    elsif params[:kid_friendly]
      @rentals = Rental.published.kid_friendly
    elsif params[:long_term]
      @rentals = Rental.published.long_term
    else
      @rentals = Rental.published
    end
  end
  
  def show
    @rental = Rental.find(params[:id])
    render nothing: true, status: 404 unless @rental.published
  end
end

app/views/rentals/_contact.html.haml
#contact.container
  .container
    -if flash[:success]
      .alert.alert-success
        =flash[:success]

    -if flash[:error]
      .alert.alert-error
        =flash[:error]

    -if flash[:notice]
      .alert.alert-info
        =flash[:notice]
    
  -unless flash[:success]
    =form_tag contacts_path do
      .row
        =text_field :contact, :from, 'data-behaviour' => 'datepicker', placeholder: 'From', class: 'input-small'
        =text_field :contact, :to, 'data-behaviour' => 'datepicker', placeholder: 'To', class: 'input-small'
      .row
        =text_field :contact, :first_name, placeholder: 'First Name', class: 'input-xlarge'
        =text_field :contact, :last_name, placeholder: 'Last Name', class: 'input-xlarge'
      .row
        =text_field :contact, :email, placeholder: 'Email', class: 'input-xlarge'
        =text_field :contact, :phone, placeholder: 'Phone', class: 'input-xlarge'
      .row
        =text_area :contact, :message, placeholder: 'Message'
        =submit_tag 'Book It', class: 'btn btn-large btn-success'



  

app/views/rentals/_rental.html.haml
.span4
  =link_to rental_path(rental) do
    =image_tag rental.featured_photo.asset.url(:medium), class: 'img-polaroid', alt: "rental photo #{rental.featured_photo.id}"
  %h2
    =rental.name
  %p
    =rental.description
  %p
    =link_to 'View details &raquo;'.html_safe, rental_path(rental), class: 'btn btn-info'

app/views/rentals/index.html.haml
#rentals
  #main.container
    -offset = 0
    -while offset < @rentals.count
      .row
        -@rentals[offset..(offset + 2)].each do |rental|
          =render partial: 'rental', object: rental
        -offset += 3

app/views/rentals/show.html.haml
#rental-details
  #main.container-fluid
    .row-fluid
      .span8
        =link_to @rental.featured_photo.asset.url(:original), target: '_blank' do
          =image_tag @rental.featured_photo.asset.url(:large), class: 'img-polaroid'

      .span4
        %h1 
          =@rental.name
        %h4
          ="Daily: $#{@rental.rate_per_night}"
        -if @rental.rate_per_week.present?
          %h4
            ="Weekly: $#{@rental.rate_per_week}"
        -if @rental.rate_per_month.present?
          %h4
            ="Monthly: $#{@rental.rate_per_month}"

        #amenities.row-fluid
          -if @rental.pet_friendly
            .amenity.span2
              =image_tag 'pet-friendly.png', alt: 'Pet Friendly', 'data-toggle' => 'tooltip', 'data-original-title' => 'Pet Friendly', class: 'icon'
          -if @rental.kid_friendly
            .amenity.span2
              =image_tag 'kid-friendly.png', alt: 'Kid Friendly', 'data-toggle' => 'tooltip', 'data-original-title' => 'Kid Friendly', class: 'icon'

        %p.lead
          =@rental.description
          
        %p
          ="#{@rental.bedrooms} Bedrooms  #{@rental.bathrooms} Bathrooms"
        

  =render partial: 'contact'
      
  #top.container-fluid
    .row-fluid
      -offset = 0
      -while offset < @rental.photos.count
        .row
          -@rental.photos[offset..(offset + 2)].each do |photo|
            .span4
              =link_to photo.asset.url(:original), target: '_blank' do
                =image_tag photo.asset.url(:medium), class: 'img-polaroid'
          -offset += 3