config/routes.rb
Rentals::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}
  

  root to: 'welcome#index'

  get 'mr_rogers' => 'mr_rogers/dashboard#index'
  
  namespace :mr_rogers do
    resources :rentals do
      post 'publish'
      post 'unpublish'
    end
    resources :photos, except: [:edit]
  end

  get 'rentals/pet_friendly' => 'rentals#index', pet_friendly: true, as: 'pet_friendly_rentals'
  get 'rentals/kid_friendly' => 'rentals#index', kid_friendly: true, as: 'kid_friendly_rentals'
  get 'rentals/long_term' => 'rentals#index', long_term: true, as: 'long_term_rentals'
  resources :rentals, only: [:show, :index]
  resources :contacts, only: [:create]
end

app/models/rental.rb
class Rental < ActiveRecord::Base
  validates :name, presence: true, :length => { :in => 2..255 }
  validates :description, presence: true, :length => { :in => 50..255 }
  validates :contact, presence: true, :length => { :in => 5..255 }
  
  has_many :photos, :dependent => :destroy

  scope :featured, -> { includes(:photos).where('photos.featured is true').references(:photos) }
  scope :banner, -> { includes(:photos).where('photos.banner is true').references(:photos) }
  scope :pet_friendly, -> { where(pet_friendly: true) }
  scope :kid_friendly, -> { where(kid_friendly: true) }
  scope :long_term, -> { where(long_term: true) }
  scope :published, -> { where(published: true) }

  def featured_photo
    if photos.empty?
      ''
    elsif photos.featured.empty?
      photos.first
    else
      photos.featured.first
    end
  end
  
  def banner_photo
    if photos.empty?
      ''
    elsif photos.banner.empty?
      photos.first
    else
      photos.banner.first
    end
  end
  
  def publish!
    update_attribute(:published, true) if photos.count > 0
  end

  def unpublish!
    update_attribute(:published, false)
  end
end

app/controllers/mr_rogers/application_controller.rb
class MrRogers::ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  layout 'admin'
  helper MrRogersHelper
  
    
  def flashy(obj)
    if obj.errors.empty?
      flash.now[:success] = 'Saved successfully'
    else
      flash.now[:error] = 'There was an error saving'
    end
  end
end

app/controllers/mr_rogers/dashboard_controller.rb
class MrRogers::DashboardController < MrRogers::ApplicationController
  def index
  end
end

app/controllers/mr_rogers/photos_controller.rb
class MrRogers::PhotosController < MrRogers::ApplicationController
  respond_to :json

  def index
    @photos = Photo.all
    render json: @photos.map{|photo| photo.to_jq_photo }
  end

  def show
    @photo = Photo.find(params[:id])
    render json: @photo
  end

  def new
    @photo = Photo.new
    render json: @photo
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def create
    @photo = Photo.new(post_params)
    begin
      if @photo.save
        render json: {files: [@photo.to_jq_photo]}, status: :created, location: [:mr_rogers, @photo]
      else
        render json: @photo.errors, status: :unprocessable_entity
      end
    rescue => e
      render json: {"error" => e}, status: :unprocessable_entity
    end
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(post_params)
      head :no_content
    else
      render json: @photo.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    head :no_content
  end

  private
    def post_params
      new_params = params
      new_params[:photo][:asset] = params[:photo][:asset].first unless new_params[:photo][:asset].nil?
      new_params.require(:photo).permit(:rental_id, :asset, :banner, :featured)
    end
  
end

app/controllers/mr_rogers/rentals_controller.rb
class MrRogers::RentalsController < MrRogers::ApplicationController
  respond_to :html
  
  def index
    respond_to do |format|
      format.html
      format.json { render json: RentalsDatatable.new(view_context) }
    end
  end
  
  def new
    @rental = Rental.new
  end
  
  def create
    @rental = Rental.create(post_params)
    flashy(@rental)
    @rental.errors.empty? ? (redirect_to action: :index) : (render :new)
  end

  def edit
    @rental = Rental.find(params[:id])
  end

  def update
    @rental = Rental.find(params[:id])
    @rental.update_attributes(post_params)
    flashy(@rental)
    render :edit
  end

  def publish
    @rental = Rental.find(params[:rental_id])
    @rental.publish!
    if @rental.published?
      flash[:success] = 'Published Successfully'
    else
      flash[:error] = 'Could not publish the rental. Check your data and try again.'
    end
    render :edit
  end

  def unpublish
    @rental = Rental.find(params[:rental_id])
    @rental.unpublish!
    if @rental.published?
      flash[:error] = 'Could not un-publish the rental for an unknown reason.'
    else
      flash[:success] = 'Un-Published Successfully'
    end
    render :edit
  end

  
  def destroy
    Rental.find(params[:id]).destroy
    flash[:success] = 'The rental has been deleted'
    redirect_to action: :index
  end

  private
    def post_params
       params.require(:rental).permit(:name, :description, :pet_friendly, :kid_friendly, :long_term, :bedrooms, :bathrooms, :rate_per_night, :rate_per_week, :rate_per_month, :contact, :base_rate_per_night, :base_rate_per_month, :base_rate_per_week, :published)
    end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  def index
    if params[:pet_friendly]
      @rentals = Rental.published.pet_friendly
    elsif params[:kid_friendly]
      @rentals = Rental.published.kid_friendly
    elsif params[:long_term]
      @rentals = Rental.published.long_term
    else
      @rentals = Rental.published
    end
  end
  
  def show
    @rental = Rental.find(params[:id])
    render nothing: true, status: 404 unless @rental.published
  end
end

app/helpers/mr_rogers_helper.rb
module MrRogersHelper
  def admin_nav_class(link)
    'active' if controller.controller_name.downcase.include?(link)
  end
  
  def input_class(obj, attribute)
    'error' unless obj.errors.messages[attribute].blank?
  end
  
  def input_error_help(obj, attribute)
    Haml::Engine.new("%span.help-inline #{obj.errors.messages[attribute]}").render unless obj.errors.messages[attribute].blank?
  end
end

app/views/mr_rogers/rentals/_form.html.haml
=form_for [:mr_rogers, @rental], class: 'form-horizontal' do |f|
  .control-group{class: input_class(@rental,:name) }
    %label.control-label{for: 'rental_name'} Name
    .controls
      =f.text_field :name, placeholder: 'Name', class: 'input-block-level'
      =input_error_help(@rental, :name)
          
  .control-group{class: input_class(@rental,:description) }
    %label.control-label{for: 'rental_description'} Description
    .controls
      =f.text_area :description, placeholder: 'Description', class: 'input-block-level', rows: 5
      =input_error_help(@rental, :description)

  .control-group{class: input_class(@rental,:bedrooms) }
    %label.control-label{for: 'rental_bedrooms'} Bedrooms
    .controls
      =f.text_field :bedrooms, placeholder: 'Bedrooms', class: 'input-small'

  .control-group{class: input_class(@rental,:bathrooms) }
    %label.control-label{for: 'rental_bathrooms'} Bathrooms
    .controls
      =f.text_field :bathrooms, placeholder: 'Bathrooms', class: 'input-small'
      
  .control-group{class: input_class(@rental,:rate_per_night) }
    %label.control-label{for: 'rental_rate_per_night'} Customer rate per night
    .controls
      $
      =f.text_field :rate_per_night, placeholder: 'Customer rate per night', class: 'input-large'

  .control-group{class: input_class(@rental,:rate_per_week) }
    %label.control-label{for: 'rental_rate_per_week'} Customer rate per week
    .controls
      $
      =f.text_field :rate_per_week, placeholder: 'Customer rate per week', class: 'input-large'

  .control-group{class: input_class(@rental,:rate_per_month) }
    %label.control-label{for: 'rental_rate_per_month'} Customer rate per month
    .controls
      $
      =f.text_field :rate_per_month, placeholder: 'Customer rate per month', class: 'input-large'
    
  .control-group
    .controls.controls-row
      .span2{class: input_class(@rental,:pet_friendly) }
        %label.checkbox{for: 'rental_pet_friendly'}
          =f.check_box :pet_friendly
          Pet Friendly
      .span2{class: input_class(@rental,:kid_friendly) }
        %label.checkbox{for: 'rental_kid_friendly'}
          =f.check_box :kid_friendly
          Kid Friendly
      .span2{class: input_class(@rental,:long_term) }
        %label.checkbox{for: 'rental_long_term'}
          =f.check_box :long_term
          Long Term

  .control-group{class: input_class(@rental,:contact) }
    %label.control-label{for: 'rental_contact'} Owner/Manager Contact Information
    =input_error_help(@rental, :contact)
    .controls
      =f.text_area :contact, placeholder: 'Owner/Manager Contact Information', class: 'input-block-level', rows: 5

  .control-group{class: input_class(@rental,:base_rate_per_night) }
    %label.control-label{for: 'rental_base_rate_per_night'} Base rate per night
    .controls
      $
      =f.text_field :base_rate_per_night, placeholder: 'Base rate per night', class: 'input-medium'

  .control-group{class: input_class(@rental,:base_rate_per_week) }
    %label.control-label{for: 'rental_base_rate_per_week'} Base rate per week
    .controls
      $
      =f.text_field :base_rate_per_week, placeholder: 'Base rate per week', class: 'input-medium'

  .control-group{class: input_class(@rental,:base_rate_per_month) }
    %label.control-label{for: 'rental_base_rate_per_month'} Base rate per month
    .controls
      $
      =f.text_field :base_rate_per_month, placeholder: 'Base rate per month', class: 'input-medium'

  .control-group
    %button.btn.btn-info{type: 'submit'} Save

app/views/mr_rogers/rentals/edit.html.haml
%h1 Edit Rental

-if @rental.published?
  .alert.alert-info
    %h2 Published
  
%ul.thumbnails
  -@rental.photos.each do |photo|
    %li.span2.text-center
      .thumbnail
        %p
          =image_tag(photo.asset.url(:thumb))
        %p
          =link_to 'Banner', mr_rogers_photo_path(id: photo.id, photo: { banner: false }), method: 'PATCH', remote: true, class: "unbanner btn btn-primary #{'hide' unless photo.banner}"
          =link_to 'Banner', mr_rogers_photo_path(id: photo.id, photo: { banner: true }), method: 'PATCH', remote: true, class: "banner btn #{'hide' if photo.banner}"
        %p
          =link_to 'Featured', mr_rogers_photo_path(id: photo.id, photo: { featured: false }), method: 'PATCH', remote: true, class: "unfeature btn btn-primary #{'hide' unless photo.featured}"
          =link_to 'Featured', mr_rogers_photo_path(id: photo.id, photo: { featured: true }), method: 'PATCH', remote: true, class: "feature btn #{'hide' if photo.featured}"

        =link_to 'Delete', mr_rogers_photo_path(photo), method: 'DELETE', data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', remote: true

=render partial: 'mr_rogers/photos/form'


=render partial: 'form'

-if @rental.published?
  =link_to 'Un-publish', mr_rogers_rental_unpublish_path(@rental), method: :POST, class: 'btn', data: { confirm: 'This will hide the rental from the public website. Are you sure you want to un-publish?' }
-else
  =link_to 'Publish', mr_rogers_rental_publish_path(@rental), method: :POST, class: 'btn btn-success', data: { confirm: 'This will make the rental show up on the public website. Are you sure you want to publish?' } 




=link_to 'Delete Rental', mr_rogers_rental_path(@rental), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger pull-right' unless @rental.id.nil?

app/views/mr_rogers/rentals/index.html.haml
%h1 All Rentals

.navbar
  .navbar-inner
    %ul.nav
      %li
        =link_to 'New', new_mr_rogers_rental_path

%table.datatable.table.table-hover.table-striped.table-bordered{'data-source' => mr_rogers_rentals_url(format: 'json')}
  %thead
    %tr
      %th ID
      %th Name
      %th Description
      %th Published
      %th Photo
  %tbody

app/views/mr_rogers/rentals/new.html.haml
%h1 New Rental

=render partial: 'form'